INSERT INTO predmeti (id, ime, ects) VALUES (1, 'Afina in projektivna geometrija', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (2, 'Aktuarska matematika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (3, 'Algebra 1', 14);
INSERT INTO predmeti (id, ime, ects) VALUES (4, 'Algebra 1 (FiM)', 14);
INSERT INTO predmeti (id, ime, ects) VALUES (5, 'Algebra 2', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (6, 'Algebra 3', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (7, 'Algebraična topologija 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (8, 'Algebraične krivulje', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (9, 'Algebra in diskretna matematika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (10, 'Algoritmi in podatkovne strukture 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (11, 'Algoritmi in podatkovne strukture 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (12, 'Analitična mehanika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (13, 'Analiza 1 (FiM)', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (14, 'Analiza 1 (IŠRM)', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (15, 'Analiza 1', 18);
INSERT INTO predmeti (id, ime, ects) VALUES (16, 'Analiza 2', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (17, 'Analiza 2a', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (18, 'Analiza 2b', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (19, 'Analiza 3 (IŠRM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (20, 'Analiza 3', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (21, 'Analiza 3 (FiM)', 9);
INSERT INTO predmeti (id, ime, ects) VALUES (22, 'Analiza 4', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (23, 'Analiza podatkov s programom R', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (24, 'Angleški jezik nivo A', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (25, 'Angleški jezik nivo B', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (26, 'Angleški jezik nivo C', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (27, 'Arhitektura računalniških sistemov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (28, 'Astronomija', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (29, 'Brezžična in mobilna omrežja', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (30, 'Davki in davčna harmonizacija v EU', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (31, 'Davki in poslovanje podjetij', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (32, 'Denar in finance', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (33, 'Didaktika 1', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (34, 'Didaktika matematike 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (35, 'Didaktika matematike 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (36, 'Diferencialna geometrija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (37, 'Diferencialne enačbe', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (38, 'Digitalno načrtovanje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (39, 'Dinamično modeliranje (I1)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (40, 'Diskretna matematika 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (41, 'Diskretna matematika 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (42, 'Diskretne strukture 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (43, 'Diskretne strukture 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (44, 'Diskretno modeliranje (I1)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (45, 'Ekonometrija 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (46, 'Ekonometrija 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (47, 'Ekonomske politike EU', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (48, 'Elektronsko poslovanje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (49, 'Elementarna geometrija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (50, 'Elementarna teorija števil', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (51, 'Evropski monetarni sistem', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (52, 'Finančna analiza 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (53, 'Finančna analiza 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (54, 'Finančna ekonomija', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (55, 'Finančna matematika 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (56, 'Finančna matematika 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (57, 'Finančna matematika 3', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (58, 'Finančni praktikum', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (59, 'Fizika 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (60, 'Fizika 2 (FMT)', 19);
INSERT INTO predmeti (id, ime, ects) VALUES (61, 'Fizika 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (62, 'Fizikalni praktikum', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (63, 'Inteligentni sistemi', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (64, 'Izbrana poglavja iz diskretne matematike 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (65, 'Izbrana poglavja iz fizike', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (66, 'Izbrana poglavja iz matematike', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (67, 'Izbrana poglavja iz praktične matematike', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (68, 'Izbrana poglavja iz računalniške matematike (računska geometrija)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (69, 'Izbrana poglavja iz računalniške matematike (simbolno računanje)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (70, 'Izbrana poglavja iz računalništva in informatike (Analiza omrežij)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (71, 'Izbrana poglavja iz teorije iger', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (72, 'Izbrane teme iz analize podatkov', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (73, 'Izračunljivost in računska zahtevnost', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (74, 'Javne finance', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (75, 'Javne finance 2', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (76, 'Kombinatorika', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (77, 'Komuniciranje v matematiki', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (78, 'Komunikacijski protokoli', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (79, 'Kvantitativne vedenjske finance', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (80, 'Linearna algebra (IŠRM)', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (81, 'Linearna algebra (PrM)', 13);
INSERT INTO predmeti (id, ime, ects) VALUES (82, 'Logika in množice', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (83, 'Makroekonomija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (84, 'Makroekonomija 3', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (85, 'Management finančnih institucij 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (86, 'Matematična orodja v fiziki', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (87, 'Matematični modeli v biologiji', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (88, 'Matematični seminar', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (89, 'Matematično izražanje v angleškem jeziku', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (90, 'Matematično modeliranje', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (91, 'Matematično modeliranje (I1)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (92, 'Matematika 1', 17);
INSERT INTO predmeti (id, ime, ects) VALUES (93, 'Matematika 1 (Fiz)', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (94, 'Matematika 2', 13);
INSERT INTO predmeti (id, ime, ects) VALUES (95, 'Matematika 2 (Fiz)', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (96, 'Matematika 2 (FMT)', 16);
INSERT INTO predmeti (id, ime, ects) VALUES (97, 'Matematika v praksi', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (98, 'Matematika z računalnikom', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (99, 'Mednarodna trgovinska politika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (100, 'Mednarodne finance', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (101, 'Mednarodne finance 2', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (102, 'Mednarodno finančno okolje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (103, 'Mehanika', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (104, 'Mehanika 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (105, 'Mikroekonomija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (106, 'Mikroekonomija 3', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (107, 'Modeliranje in upravljanje sistemov (I1)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (108, 'Modeliranje računalniških omrežij', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (109, 'Modeli vrednotenja naložb', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (110, 'Monetarna ekonomija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (111, 'Monetarna ekonomija 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (112, 'Multimedijski sistemi', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (113, 'Multivariatna analiza', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (114, 'Napredni pristopi v programskem okolju R', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (115, 'Nekomutativna algebra', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (116, 'Numerična integracija in navadne diferencialne enačbe', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (117, 'Numerične metode', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (118, 'Numerične metode 1 (FiM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (119, 'Numerične metode 1 (PrM)', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (120, 'Numerične metode 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (121, 'Numerične metode za linearne sisteme upravljanja', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (122, 'Obvladovanje tveganj', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (123, 'Operacijske raziskave (2. letnik)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (124, 'Operacijske raziskave (3. letnik)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (125, 'Optimizacija', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (126, 'Optimizacija v financah', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (127, 'Optimizacijske metode (FiM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (128, 'Optimizacijske metode (IŠRM)', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (129, 'Organizacija in management', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (130, 'Organizacija in struktura trga', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (131, 'Osnove digitalnih vezij', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (132, 'Osnove oblikovanja', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (133, 'Osnove podatkovnih baz (FiM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (134, 'Osnove podatkovnih baz (IŠRM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (135, 'Osnove umetne inteligence', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (136, 'Parcialne diferencialne enačbe (PrM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (137, 'Parcialne diferencialne enačbe', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (138, 'Pedagogika z andragogiko', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (139, 'Planiranje in upravljanje informatike', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (140, 'Podatkovne baze 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (141, 'Podatkovne baze 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (142, 'Podatkovne strukture in algoritmi 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (143, 'Podatkovne strukture in algoritmi 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (144, 'Porazdeljeni sistemi', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (145, 'Poslovne finance 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (146, 'Poslovne finance 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (147, 'Posplošeni linearni modeli', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (148, 'Postopki razvoja programske opreme', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (149, 'Praktično usposabljanje', 15);
INSERT INTO predmeti (id, ime, ects) VALUES (150, 'Prevajalniki', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (151, 'Principi programskih jezikov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (152, 'Programiranje 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (153, 'Programiranje 1 (IŠRM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (154, 'Programiranje 1 (PrM)', 9);
INSERT INTO predmeti (id, ime, ects) VALUES (155, 'Programiranje 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (156, 'Programiranje 2 (IŠRM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (157, 'Programiranje 3', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (158, 'Programiranje specifičnih platform', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (159, 'Programska oprema pri pouku', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (160, 'Proseminar', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (161, 'Proseminar A', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (162, 'Proseminar B', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (163, 'Računalniška grafika in tehnologija iger', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (164, 'Računalniška orodja v matematiki', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (165, 'Računalniške komunikacije', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (166, 'Računalniški praktikum (PrM)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (167, 'Računalniški praktikum (FiM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (168, 'Računalniški praktikum (Fiz)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (169, 'Računalniški praktikum (FMT)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (170, 'Računalniški praktikum', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (171, 'Računalniško podprto (geometrijsko) oblikovanje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (172, 'Računalništvo 1', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (173, 'Računalništvo 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (174, 'Računalništvo v praksi 1', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (175, 'Računalništvo v praksi 2', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (176, 'Računska zahtevnost in hevristično programiranje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (177, 'Računsko zahtevne metode', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (178, 'Razvoj informacijskih sistemov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (179, 'Razvoj inteligentnih sistemov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (180, 'Seminar', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (181, 'Seminar 1 (skupaj)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (182, 'Seminar 2 (skupaj)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (183, 'Simbolno računanje in dinamična geometrija', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (184, 'Sistemska programska oprema', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (185, 'Slučajni procesi 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (186, 'Spletno programiranje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (187, 'Splošna topologija', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (188, 'Statistično obvladovanje procesov', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (189, 'Statistika', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (190, 'Statistika 1', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (191, 'Statistika v šoli', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (192, 'Tehnologija upravljanja podatkov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (193, 'Temelji finančnega in poslovodnega računovodstva', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (194, 'Teorija grafov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (195, 'Teorija iger', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (196, 'Teorija informacij in pogodb v financah in zavarovalništvu', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (197, 'Teorija izračunljivosti', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (198, 'Teorija kodiranja in kriptografija', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (199, 'Umetno zaznavanje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (200, 'Uvod v algebraično geometrijo', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (201, 'Uvod v diferencialno geometrijo', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (202, 'Uvod v fiziko', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (203, 'Uvod v funkcionalno analizo', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (204, 'Uvod v geometrijsko topologijo', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (205, 'Uvod v numerične metode', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (206, 'Uvod v odkrivanje znanj iz podatkov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (207, 'Uvod v programiranje (FiM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (208, 'Uvod v programiranje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (209, 'Verjetnost', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (210, 'Verjetnost (PrM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (211, 'Verjetnost 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (212, 'Verjetnost 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (213, 'Verjetnost in statistika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (214, 'Verjetnostni račun in statistika', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (215, 'Zanesljivost in zmogljivost računalniških sistemov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (216, 'Zgodovina matematike', 5);