INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2890, 'Denis', 'Arčon', 'denis.arcon@fmf.uni-lj.si', 'F424');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (29124, 'Franci', 'Bajd', 'franci.bajd@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2909, 'Vladimir', 'Batagelj', 'vladimir.batagelj@fmf.uni-lj.si', 'M406');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2912, 'Andrej', 'Bauer', 'andrej.bauer@fmf.uni-lj.si', 'M435');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (8763, 'Gregor', 'Bavdek', 'gregor.bavdek@fmf.uni-lj.si', 'F008');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2921, 'Janez', 'Bernik', 'janez.bernik@fmf.uni-lj.si', 'M502');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22755, 'Marko', 'Boben', 'marko.boben@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2927, 'Drago', 'Bokal', 'drago.bokal@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2930, 'Janez', 'Bonča', 'janez.bonca@fmf.uni-lj.si', 'F402');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (11200, 'Matej', 'Brešar', 'matej.bresar@fmf.uni-lj.si', 'M423');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (12718, 'Andraž', 'Briški Javor', 'andraz.briskijavor@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2936, 'Anita', 'Buckley', 'anita.buckley@fmf.uni-lj.si', 'M507');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2939, 'Sergio', 'Cabello', 'sergio.cabello "AT" fmf.uni-lj.si', 'M411');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2957, 'Andrej', 'Čadež', 'andrej.cadez@fmf.uni-lj.si', 'F213');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27090, 'Matija', 'Cencelj', 'matija.cencelj (at) pef.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2965, 'Miran', 'Černe', 'miran.cerne@fmf.uni-lj.si', 'M429');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2942, 'Gregor', 'Cigler', 'gregor.cigler@fmf.uni-lj.si', 'M508');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2945, 'Jakob', 'Cimprič', 'jaka.cimpric@fmf.uni-lj.si', 'M421');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (4355, 'Leon', 'Cizelj', 'Leon.Cizelj@ijs.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (17096, 'Simon', 'Čopar', 'simon.copar@fmf.uni-lj.si', 'F410');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2968, 'Martin', 'Čopič', 'martin.copic@fmf.uni-lj.si', 'F106');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2951, 'Dean', 'Cvetko', 'dean.cvetko@fmf.uni-lj.si', 'F416, F008');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2954, 'Karin', 'Cvetko Vah', 'karin.cvetko@fmf.uni-lj.si', 'M503');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2983, 'Mirko', 'Dobovišek', 'mirko.dobovisek@fmf.uni-lj.si', 'M520');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2989, 'Janez', 'Dolinšek', 'janez.dolinsek@fmf.uni-lj.si', 'F428');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2995, 'David', 'Dolžan', 'david.dolzan@fmf.uni-lj.si', 'M503');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2998, 'Oliver', 'Dragičević', 'oliver.dragicevic@fmf.uni-lj.si', 'M516');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3001, 'Irena', 'Drevenšek Olenik', 'irena.drevensek@fmf.uni-lj.si', 'F421');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3007, 'Barbara', 'Drinovec Drnovšek', 'barbara.drinovec@fmf.uni-lj.si', 'M425');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3028, 'Roman', 'Drnovšek', 'roman.drnovsek@fmf.uni-lj.si', 'M402');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (7368, 'Andreja', 'Drobnič Vidic', 'andreja.drobnic@fmf.uni-lj.si', 'F5.04');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (18014, 'Dunja', 'Fabjan', 'dunja.fabjan@fmf.uni-lj.si', 'F423');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3031, 'Svjetlana', 'Fajfer', 'svjetlana.fajfer@fmf.uni-lj.si', 'F427');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9577, 'Sergej', 'Faletič', 'sergej.faletic@fmf.uni-lj.si', 'F213');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (39700, 'Karla', 'Ferjančič', 'karla.ferjancic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3037, 'Franc', 'Forstnerič', 'franc.forstneric@fmf.uni-lj.si', 'M424');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3045, 'Josip', 'Globevnik', 'josip.globevnik@fmf.uni-lj.si', 'F305');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14437, 'Mihael', 'Gojkošek', 'gojkosek@fmf.uni-lj.si', 'F204');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3048, 'Boštjan', 'Golob', 'bostjan.golob@fmf.uni-lj.si', 'F416');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34639, 'Dejan', 'Govc', 'dejan.govc@imfm.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3060, 'Darja', 'Govekar-Leban', 'darja.govekar@fmf.uni-lj.si', 'M519');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34783, 'Jan', 'Grošelj', 'jan.groselj@fmf.uni-lj.si', 'F515');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3063, 'Milan', 'Hladnik', 'milan.hladnik@fmf.uni-lj.si', 'F320');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3069, 'Martin', 'Horvat', 'martin.horvat@fmf.uni-lj.si', 'F418');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34634, 'Barbara', 'Ikica', 'barbara.ikica@imfm.si', 'F318');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3087, 'Gašper', 'Jaklič', 'gasper.jaklic@fmf.uni-lj.si', 'M515');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (25858, 'Sonja', 'Jejčič', 'sonja.jejcic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22297, 'Blaž', 'Jelenc', 'blaz.jelenc@fmf.uni-lj.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (32716, 'Robert', 'Jeraj', 'robert.jeraj@fmf.uni-lj.si', 'F422');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3103, 'Marjan', 'Jerman', 'marjan.jerman@fmf.uni-lj.si', 'M502');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3109, 'Martin', 'Jesenko', 'martin.jesenko@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (24311, 'Urban', 'Jezernik', 'urban.jezernik@fmf.uni-lj.si', 'M5.11');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3118, 'Martin', 'Juvan', 'martin.juvan@fmf.uni-lj.si', 'M411');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3121, 'Jure', 'Kališnik', 'jure.kalisnik@fmf.uni-lj.si', 'F310, M514');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9466, 'Marko', 'Kandić', 'marko.kandic@fmf.uni-lj.si', 'M513');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3127, 'Borut Paul', 'Kerševan', 'borut.kersevan@ijs.si', 'F430');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (7314, 'Gregor', 'Kladnik', 'gregor.kladnik@fmf.uni-lj.si', 'F008');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (10778, 'Sandi', 'Klavžar', 'Sandi.Klavzar@fmf.uni-lj.si', 'F403');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (25514, 'Ivo', 'Kljenak', 'ivo.kljenak@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3142, 'Damjan', 'Kobal', 'damjan.kobal@fmf.uni-lj.si', 'MP28 (pritličje)');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3145, 'Pino', 'Koc', 'pino.koc@fmf.uni-lj.si', 'MP25 (pritličje)');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (35201, 'Angela', 'Kochoska', 'angela.kochoska@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3151, 'Alojzij Franc', 'Kodre', 'alojz.kodre@fmf.uni-lj.si', 'F401');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (25508, 'Boštjan', 'Končar', 'bostjan.koncar@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (17137, 'Matjaž', 'Konvalinka', 'matjaz.konvalinka@fmf.uni-lj.si', 'F414');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14351, 'Drejc', 'Kopač', 'drejc.kopac@fmf.uni-lj.si', 'F214');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3169, 'Tomaž', 'Košir', 'tomaz.kosir@fmf.uni-lj.si', 'M4.31');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27909, 'Nejc', 'Košnik', 'nejc.kosnik@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3172, 'Jernej', 'Kozak', 'jernej.kozak@fmf.uni-lj.si', 'M407');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3175, 'Marjetka', 'Krajnc', 'marjetka.krajnc@fmf.uni-lj.si', 'M515');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3178, 'Edvard', 'Kramar', 'edvard.kramar@fmf.uni-lj.si', 'M428');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3184, 'Peter', 'Križan', 'peter.krizan@fmf.uni-lj.si', 'F428');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22300, 'Matjaž', 'Krnc', 'matjaz.krnc@fmf.uni-lj.si', 'F318');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22303, 'Uroš', 'Kuzman', 'uros.kuzman@gmail.com', 'M510');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3193, 'Gojmir', 'Lahajnar', 'gojmir.lahajnar@fmf.uni-lj.si', 'F428');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3204, 'Boris', 'Lavrič', 'boris.lavric@fmf.uni-lj.si', 'M434');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3207, 'Peter', 'Legiša', 'peter.legisa@fmf.uni-lj.si', 'M422');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3210, 'Davorin', 'Lešnik', 'davorin.lesnik@fmf.uni-lj.si', 'MP.20');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3213, 'Andrej', 'Likar', 'andrej.likar@fmf.uni-lj.si', 'F419');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2854, 'Matija', 'Lokar', 'matija.lokar@fmf.uni-lj.si', 'M506');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3228, 'Bojan', 'Magajna', 'bojan.magajna@fmf.uni-lj.si', 'M430');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (39731, 'Boris', 'Majaron', 'boris.majaron@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (29119, 'Aleksej', 'Majkić', 'aleksej.majkic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3237, 'Norma Susana', 'Mankoč Borštnik', 'norma.mankoc@fmf.uni-lj.si', 'F105');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34692, 'Tilen', 'Marc', 'tilen.marc@imfm.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14284, 'Janko', 'Marovt', 'janko.marovt@uni-mb.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27902, 'Ugo', 'Marzolino', 'ugo.marzolino@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (4332, 'Borut', 'Mavko', 'borut.mavko@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (31614, 'Marko', 'Medenjak', 'marko.medenjak@fmf.uni-lj.si', 'F408a');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3249, 'George', 'Mejak', 'george.mejak@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3252, 'Tomaž', 'Mertelj', 'tomaz.mertelj@fmf.uni-lj.si', 'F409');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9405, 'Dragan', 'Mihailović', 'dragan.mihailovic@ijs.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3258, 'Marko', 'Mikuž', 'marko.mikuz@fmf.uni-lj.si', 'F410');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (33907, 'Matija', 'Milanič', 'matija.milanic@fmf.uni-lj.si', 'F422');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3261, 'Bojan', 'Mohar', 'bojan.mohar@fmf.uni-lj.si', 'F303');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3264, 'Aleš', 'Mohorič', 'ales.mohoric@fmf.uni-lj.si', 'F201');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3270, 'Primož', 'Moravec', 'primoz.moravec@fmf.uni-lj.si', 'M412');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3273, 'Janez', 'Mrčun', 'janez.mrcun@fmf.uni-lj.si', 'M405');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3279, 'Igor', 'Muševič', 'igor.musevic@fmf.uni-lj.si', 'F403');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3294, 'Nika', 'Novak', 'nika.novak@fmf.uni-lj.si', 'M518');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3300, 'Matjaž', 'Omladič', 'matjaz.omladic@fmf.uni-lj.si', 'M432, F314');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3303, 'Alen', 'Orbanić', 'alen.orbanic@fmf.uni-lj.si', 'M518');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3315, 'Natan', 'Osterman', 'natan.osterman at fmf.uni-lj.si', 'FP16, FP17');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14358, 'Nina', 'Otopal', 'nina.klenovsek@imfm.si', 'F316');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3321, 'Petar', 'Pavešić', 'petar.pavesic@fmf.uni-lj.si', 'M408');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27918, 'Mihael', 'Perman', 'mihael.perman@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3336, 'Marko', 'Petkovšek', 'marko.petkovsek@fmf.uni-lj.si', 'M409');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3342, 'Tomaž', 'Pisanski', 'tomaz.pisanski@fmf.uni-lj.si', 'M517');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3351, 'Gorazd', 'Planinšič', 'gorazd.planinsic@fmf.uni-lj.si', 'F207');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3357, 'Bor', 'Plestenjak', 'bor.plestenjak@fmf.uni-lj.si', 'M404');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22313, 'Lucijan', 'Plevnik', 'lucijan.plevnik@fmf.uni-lj.si', 'M511');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3366, 'Rudolf', 'Podgornik', 'rudolf.podgornik@fmf.uni-lj.si', 'F405');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3372, 'Tomaž', 'Podobnik', 'tomaz.podobnik@fmf.uni-lj.si', 'F112');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27892, 'Vid', 'Podpečan', 'vid.podpecan@ijs.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3378, 'Dušan', 'Ponikvar', 'dusan.ponikvar@fmf.uni-lj.si', 'F002, F012');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3384, 'Primož', 'Potočnik', 'primoz.potocnik@fmf.uni-lj.si', 'MP27 (pritličje)');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34804, 'Matej', 'Praprotnik', 'matej.praprotnik@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3387, 'Peter', 'Prelovšek', 'peter.prelovsek@fmf.uni-lj.si', 'F101');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (7384, 'Saša', 'Prelovšek Komelj', 'sasa.prelovsek@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14143, 'Matija', 'Pretnar', 'matija.pretnar@fmf.uni-lj.si', 'M519');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3390, 'Jasna', 'Prezelj', 'jasna.prezelj@fmf.uni-lj.si', 'M510');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3393, 'Tomaž', 'Prosen', 'tomaz.prosen@fmf.uni-lj.si', 'F407');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3399, 'Martin', 'Raič', 'martin.raic@fmf.uni-lj.si', 'M512');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3402, 'Jože', 'Rakovec', 'joze.rakovec@fmf.uni-lj.si', 'F119');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3409, 'Anton', 'Ramšak', 'anton.ramsak@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3412, 'Miha', 'Ravnik', 'miha.ravnik@fmf.uni-lj.si', 'F411');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (15977, 'Marko', 'Razpet', 'marko.razpet@guest.arnes.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (4802, 'Tomaž', 'Rejec', 'tomaz.rejec@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (7477, 'Dušan', 'Repovš', 'dusan.repovs@guest.arnes.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3421, 'Mitja', 'Rosina', 'mitja.rosina@fmf.uni-lj.si', 'F422b');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3427, 'Pavle', 'Saksida', 'pavle.saksida@fmf.uni-lj.si', 'M420');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3472, 'Andreja', 'Šarlah', 'andreja.sarlah@fmf.uni-lj.si', 'F412');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3478, 'Gregor', 'Šega', 'gregor.sega@fmf.uni-lj.si', 'M512');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3430, 'Janez', 'Seliger', 'janez.seliger@fmf.uni-lj.si', 'F429');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3481, 'Peter', 'Šemrl', 'peter.semrl@fmf.uni-lj.si', 'M410');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (31259, 'Urban', 'Simončič', 'urban.simoncic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (32646, 'Alex', 'Simpson', 'Alex.Simpson@fmf.uni-lj.si', 'F4.28');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3487, 'Simon', 'Širca', 'simon.sirca@fmf.uni-lj.si', 'F417');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3493, 'Klemen', 'Šivic', 'klemen.sivic@fmf.uni-lj.si', 'M507');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3436, 'Gregor', 'Skačej', 'gregor.skacej@fmf.uni-lj.si', 'F412');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9336, 'Miha', 'Škarabot', 'miha.skarabot@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3442, 'Gregor', 'Skok', 'gregor.skok@fmf.uni-lj.si', 'F116');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3504, 'Riste', 'Škrekovski', 'riste.skrekovski@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (6844, 'Damijan', 'Škrk', 'damijan.skrk@gov.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3507, 'Žiga', 'Šmit', 'ziga.smit@fmf.uni-lj.si', 'F208');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3451, 'Jaka', 'Smrekar', 'jaka.smrekar@fmf.uni-lj.si', 'M413');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22319, 'Špela', 'Špenko', 'spela.spenko@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22463, 'Tadej', 'Starčič', 'tadej.starcic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3460, 'Janez', 'Stepišnik', 'janez.stepisnik@fmf.uni-lj.si', 'F404');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22322, 'Janez', 'Šter', 'janez.ster@imfm.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (35101, 'Jordan', 'Stoyanov', 'jordan.stoyanov@fmf.uni-lj.si', 'FP41');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9333, 'Benedikt', 'Strajnar', 'benedikt.strajnar@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3463, 'Sašo', 'Strle', 'saso.strle@fmf.uni-lj.si', 'M401');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (32872, 'Andrej', 'Studen', 'andrej.studen@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2476, 'Daniel', 'Svenšek', 'daniel.svensek@fmf.uni-lj.si', 'F413');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (6851, 'Iztok', 'Tiselj', 'iztok.tiselj@ijs.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (11259, 'Aleš', 'Toman', 'ales.toman@imfm.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3516, 'Jernej', 'Tonejc', 'jernej.tonejc@fmf.uni-lj.si', 'F312');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (25498, 'Andrej', 'Trkov', 'andrej.trkov@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3519, 'Zvonko', 'Trontelj', 'zvonko.trontelj@fmf.uni-lj.si', 'F307');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (38505, 'Riccardo', 'Ugolini', 'riccardo.ugolini@imfm.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3525, 'Aleš', 'Vavpetič', 'ales.vavpetic@fmf.uni-lj.si', 'M513');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3529, 'Dejan', 'Velušček', 'dejan.veluscek@fmf.uni-lj.si', 'M516');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27897, 'Janoš', 'Vidali', 'janos.vidali@fmf.uni-lj.si', 'M514');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (31624, 'Matija', 'Vidmar', 'matija.vidmar@fmf.uni-lj.si', 'MP18');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3535, 'Žiga', 'Virk', 'ziga.virk@fmf.uni-lj.si', 'M518');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (16068, 'Jože', 'Vrabec', 'Joze.Vrabec@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3565, 'Rahela', 'Žabkar', 'rahela.zabkar@fmf.uni-lj.si', 'F118');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22325, 'Gašper', 'Zadnik', 'zadnik@fmf.uni-lj.si', 'F310');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3571, 'Emil', 'Žagar', 'emil.zagar@fmf.uni-lj.si', 'M433');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3574, 'Nedjeljka', 'Žagar', 'nedjeljka.zagar@fmf.uni-lj.si', 'F115');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (29072, 'Aljaž', 'Zalar', 'Aljaz.Zalar@imfm.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9411, 'Boštjan', 'Zalar', 'bostjan.zalar@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3544, 'Matjaž', 'Zaveršnik', 'matjaz.zaversnik@fmf.uni-lj.si', 'MP20');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3577, 'Matjaž', 'Željko', 'matjaz.zeljko@fmf.uni-lj.si', 'M313');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3547, 'Marko', 'Zgonik', 'marko.zgonik@fmf.uni-lj.si', 'F401');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3550, 'Primož', 'Ziherl', 'primoz.ziherl@fmf.uni-lj.si', 'F204');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3580, 'Arjana', 'Žitnik', 'arjana.zitnik@fmf.uni-lj.si', 'M504');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3583, 'Marko', 'Žnidarič', 'marko.znidaric (atat) fmf.uni-lj.si', 'F406');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3589, 'Slobodan', 'Žumer', 'slobodan.zumer@fmf.uni-lj.si', 'F102');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (31256, 'Anže', 'Zupanc', 'anze.zupanc@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3559, 'Tomaž', 'Zwitter', 'tomaz.zwitter@fmf.uni-lj.si', 'F425');
